services:
  - type: web
    name: orionbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DEEPINFRA_API_KEY
        sync: false
